export { default as instagram } from './instagram.svg'
export { default as twitter } from './twitter.svg'
export { default as linkedin } from './linkedin.svg'
export { default as github } from './github.svg'
export { default as position } from './position.svg'
export { default as at } from './at.svg'
export { default as phone } from './phone.svg'